### ISSUE TITLE
Error with Script

### ISSUE THREAD

**Issue by AkhilK28** [ramSeraph/opendata#1]
Hello!

My name is Akhil, and I wanted to access LGD data via your script (to get everything all at once) but ran into an issue!

See below:
![image](https://user-images.githubusercontent.com/49628286/142957122-f058693c-4452-418a-a413-bc8397160f8e.png)

Could you let me know if there is a way to debug this?

If not, do you mind running the script and sending the data files to me?

Thank you so much! I extremely appreciate it!

Best,
Akhil

**Comment by ramSeraph** [comment]
Hey Akhil

I  have pushed some fixes. 

Please check with the latest master.

**Comment by AkhilK28** [comment]
Hello!

Thank you so much for looking into this! You are the only one who has built a tool to extract information from LGD and I'm extremely appreciative of you getting back to me!

I ran your script again following the instructions in the "Read Me" section. The first 4 files were exported successfully but the village one ran into an error I think.

Please see the full error code below.

![image](https://user-images.githubusercontent.com/49628286/143749567-06c73b03-3a05-4e81-8209-78c226269c21.png)

Let me know if you have any questions!

Best,
Akhil

**Comment by ramSeraph** [comment]
Ok. My last attempts recently haven't gone past the villages section either. 
But that wasn't the error i got. It was more of a running out of time issue. But your error feels like a breaking of connection. 

I will look into it.  I will most probably break the villages download to a statewise download and merge. 

I have one upload at https://drive.google.com/file/d/1z2Kx4J2L04oa0WSl0jeFMtIbVIrDNJrL/view?usp=sharing for 15th september which you can use.

**Comment by ramSeraph** [comment]
The debugging for this is usually me capturing the POST data and headers from a successful request in the browser and converting it to python requests library and hoping it would work :)

**Comment by ramSeraph** [comment]
Released a newer version of the code. Let me know if you are still having problems with it.

**Comment by ramSeraph** [comment]
The plan is to set up an automated process which uploads data somewhere accessible to everyone. 

I uploaded today's data here- https://drive.google.com/file/d/1Z4EerbsY-wk09blhBvchUm_-uUhwFILA/view?usp=sharing

**Comment by AkhilK28** [comment]
Hello!

This is wonderful, thank you so much! I downloaded today's data and checked the "constituencies_mapping.csv" file and wanted to double-check the number of rows in that file with LGD before using it.

For Andhra Pradesh, there were 21088 rows in the PRI version + 386 in the Urban version from LGD, which totals 21474. However, in your file for Andhra Pradesh, there were 21610 rows.

Could you let me know how the "constituencies_mapping.csv" file was constructed from the LGD data?

Thank you so much in advance!

Best,
Akhil

**Comment by ramSeraph** [comment]
I checked.. Couldn't find where the data for constituencies_mappings.csv came from. My guess is that it existed in the Download Directory section at some point of time and has been replaced by the PRI and Urban versions. 

I made the changes to pick up the Urban and PRI versions instead and pushed here.
I will add the latest download link when I complete today's download

**Comment by ramSeraph** [comment]
Link to data for 12 December 2021 - https://drive.google.com/file/d/1uU_7CnnA7Pps55O4I1P_TEjCK3uhRFvW/view?usp=sharing

**Comment by ramSeraph** [comment]
Do let me know if you want any more of the data in LGD pulled. will add the code for it.

**Comment by AkhilK28** [comment]
Hey!

Thank you so much for updating the PRI and Urban data!

Could you also update the "Constituency Coverage" LGD for each state as well?

And where can I access the daily/weekly uploaded files on Google Drive?

Thanks once again!

**Comment by ramSeraph** [comment]
Updated script to pull 'Constituency Coverage' data.. 

Currently, I have been running the script manually and uploading to my google drive and sharing links..

I plan to automate this and put the data in GCS and setup a webpage with download links. This is going to take sometime as I am experimenting with setting up things with minimal infrastructure maintenance. 

I would suggest running the script to get the data for now. Let me know if something breaks while running the script

**Comment by AkhilK28** [comment]
Hi!

We have released our NFHS District Tracker (https://geographicinsights.iq.harvard.edu/nfhs-tracker-districts) and now will be working on a related project using LGD data. My colleague will be in touch if he runs into any issues with downloading this data.

Thank you!
