### ISSUE TITLE
Error with Script 2.0

### ISSUE THREAD

**Issue by AkhilK28** [ramSeraph/opendata#2]
Hey!

Hope you're doing well! I recently ran your script again and got the following error message:

![image](https://user-images.githubusercontent.com/49628286/147432856-9b8c584d-0c1e-4a98-85a1-70fd7225786f.png)

Could you please let me know how I can get the latest LGD constituency data?

Thank you so much!

Best,
Akhil

**Comment by ramSeraph** [comment]
That looks like you are missing some the google cloud requirements. Please rerun `pip install -r requirements.txt` to pull the latest requirements and let me know if it is still an issue. Thanks.

**Comment by AkhilK28** [comment]
Hello!

Happy New Year! I just came back and I have run the updated command and I am still encountering the same error as above! Please let me know if there is anything else I should do to run this script. This was after I installed the new requirements using "pip install" See the screenshot below:

![image](https://user-images.githubusercontent.com/49628286/148274199-fd494945-9f2f-4a04-b324-fa9aae3cb0ef.png)

**Comment by ramSeraph** [comment]
Not sure what is happening there.. 

For now you can use this link to get the lgd data - https://storage.googleapis.com/lgd_data_archive/03Jan2022.zip

**Comment by AkhilK28** [comment]
Hello!

Hope you are well! I was going through the "constituency_coverage.csv" file that was in the ZIP file you shared above and wanted to double-check everything for 1 state. I found some data issues that I thought I would let you know about.

In your file for Andra Pradesh, there are only 999 rows of data but when I downloaded the Constituency Coverage data from LGD for the entire state of Andhra Pradesh into Excel -- there are over 2,500 rows of data.

Could you indicate how are doing this data pull from LGD and does your data match LGD's data or are you creating your own modified LGD dataset?

Thank you!

**Comment by ramSeraph** [comment]
That is concerning.. I will check and get back to you. There is supposed to
be no differences between the data in LGD and this. I most probably messed
up the file conversion. There were some heuristics used there which are a
little flaky.

**Comment by AkhilK28** [comment]
Thank you so much! Looking forward to hearing back!

**Comment by ramSeraph** [comment]
Sorry that I never was able to get back to you.. I never did get to validate the data in the archive. At some point of time.. I think it did start working. 

I am going to keep the issue open till I do have a proper validation framework in place

**Comment by ramSeraph** [comment]
Closing this in favour of #10
