### ISSUE TITLE
Labels in sheet not recognizable

### ISSUE THREAD

**Issue by amnmalik** [ramSeraph/opendata#3]
Some of the SOI sheets have labels/text, where certain letters are replaced by non-character signs like >, & %. Did you download the SOI specific font? https://onlinemaps.surveyofindia.gov.in/SOIFonts.aspx

**Comment by ramSeraph** [comment]
I did.. it didn't work as expected. I don't have enough expertise dealing with fonts in pdf. But if you got it working on your machine and can tell me the configuration used.. I can regenerate using that. 

This was one of the major thing that has been bothering me. 

I tried multiple pdf to image conversion options.. `mupdf` worked best.. `ghostscript` and `poppler` fared worse.

**Comment by ramSeraph** [comment]
sample pdf to try things on - https://storage.googleapis.com/soi_data/raw/57M_15.pdf

**Comment by amnmalik** [comment]
All the labels clearly show when I open it in Adobe Acrobat Pro. I am guessing that as long as labels are shown in pdf, they should show in the resulting png. How do you read your pdf files?
![image](https://user-images.githubusercontent.com/43343789/170918465-a415fedf-ec5b-4d3b-a42e-457d60fd7628.png)
 Attached the png
![57M_15](https://user-images.githubusercontent.com/43343789/170918538-08456c11-65f4-4236-8068-d1145fedf554.png)

**Comment by ramSeraph** [comment]
Command line using `mupdf`.. `mutool draw`

**Comment by ramSeraph** [comment]
Wrote some notes on the process used.. https://ramseraph.github.io/opendata/maps/SOI/notes

**Comment by ramSeraph** [comment]
Found a workaround by patching `mutool draw` to pick up fonts from a folder. Will update the whole pipeline and existing data sometime this week.

**Comment by amnmalik** [comment]
Awesome!

**Comment by ramSeraph** [comment]
All tiles and georeferenced images have been updated with better fonts.
